# Generated by Django 4.1.5 on 2023-01-20 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeToPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantable', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='at2p_app.crop')),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planter',
            name='crops',
            field=models.ManyToManyField(through='at2p_app.TimeToPlant', to='at2p_app.crop'),
        ),
    ]
