# Generated by Django 4.1.5 on 2023-01-19 00:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planter',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='planter',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
