# Generated by Django 4.1.5 on 2023-01-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropModel',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Crop ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('abs_low', models.SmallIntegerField(verbose_name='Absolute Low Temperature')),
                ('abs_high', models.SmallIntegerField(verbose_name='Absolute High Temperature')),
                ('opt_low', models.SmallIntegerField(verbose_name='Optimal Low Temperature')),
                ('opt_high', models.SmallIntegerField(verbose_name='Optimal High Temperature')),
            ],
        ),
    ]
