# Generated by Django 4.1.5 on 2023-01-19 14:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0002_planter_country_planter_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historic_avg_temp', models.SmallIntegerField(blank=True, null=True)),
                ('forecast_high_temp', models.SmallIntegerField(blank=True, null=True)),
                ('forecast_low_temp', models.SmallIntegerField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
