# Generated by Django 4.1.5 on 2023-01-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0003_weatherinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='lat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='long',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
