# Generated by Django 4.1.5 on 2023-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0004_alter_planter_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetoplant',
            name='chill',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetoplant',
            name='cook',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetoplant',
            name='plantable_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
