# Generated by Django 4.1.5 on 2023-02-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0004_remove_cropmodel_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmodel',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Crop ID'),
        ),
    ]
