# Generated by Django 4.1.5 on 2023-01-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0005_timetoplant_chill_timetoplant_cook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetoplant',
            options={'ordering': ['plantable_score']},
        ),
    ]
