# Generated by Django 4.1.6 on 2023-02-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0005_alter_cropmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='Crop ID'),
        ),
    ]
