# Generated by Django 4.1.5 on 2023-01-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0006_alter_timetoplant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetoplant',
            options={'ordering': ['-plantable_score', 'crop']},
        ),
        migrations.AddField(
            model_name='timetoplant',
            name='soil',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
