# Generated by Django 4.1.5 on 2023-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0007_alter_timetoplant_options_timetoplant_soil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='crop',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
