# Generated by Django 4.1.6 on 2023-02-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0008_placemodel_weather_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemodel',
            name='weather_id',
            field=models.UUIDField(null=True, verbose_name='Weather ID'),
        ),
    ]
