# Generated by Django 4.1.5 on 2023-01-21 17:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0008_alter_crop_options_crop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='max_opt_temp',
            field=models.SmallIntegerField(verbose_name='Optimum Upper Temperature'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='max_temp',
            field=models.SmallIntegerField(verbose_name='Maximum Temperature'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_opt_temp',
            field=models.SmallIntegerField(verbose_name='Optimum Lower Temperature'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='min_temp',
            field=models.SmallIntegerField(verbose_name='Minimum Temperature'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='planter',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='US', max_length=2, null=True),
        ),
    ]
