# Generated by Django 4.1.5 on 2023-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0009_alter_crop_max_opt_temp_alter_crop_max_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='zip',
            field=models.CharField(default=22405, max_length=10),
            preserve_default=False,
        ),
    ]
