# Generated by Django 4.1.5 on 2023-01-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at2p_app', '0010_alter_weatherinfo_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
